TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#DB += dbExample1.db
#DB += dbExample2.db
#DB += dbSubExample.db
#DB += user.substitutions
#DB += userHost.substitutions
#DB += hybLV.db
DB += dbHybT.db
DB += dbHybLVIrd_v125.db
DB += dbHybLVIrd_avdd.db
DB += dbHybLVIrd_dvdd.db
DB += dbHybLVVf_v125.db
DB += dbHybLVVf_avdd.db
DB += dbHybLVVf_dvdd.db
DB += dbHybLVVn_v125.db
DB += dbHybLVVn_avdd.db
DB += dbHybLVVn_dvdd.db
DB += dbHybLVVSetRd_v125.db
DB += dbHybLVVSetRd_avdd.db
DB += dbHybLVVSetRd_dvdd.db
DB += dbHybLVVSet.db
DB += dbHybLVStat.db
DB += dbHybridSwitch.db
DB += dbFebTemp.db
DB += dbDataDpm.db
DB += dbControlDpm.db
DB += dbDataDpmFebNum.db
DB += dbDataDpmHybNum.db
DB += dbDataDpmLink.db
DB += dbDataDpmEventCount.db
DB += dbDataDpmTrigCount.db
DB += dbDataDtmTrigCount.db
DB += dbDataDtmReadCount.db
DB += dbDataDtmAckCount.db
DB += dbDataDtm.db
DB += dbFebLayer.db
DB += dbHybSync.db
DB += dbHybSyncBase.db
DB += dbHybSyncPeak.db
DB += dbControlDpmStatus.db
DB += dbDataDpmStatus.db
DB += dbDataDtmStatus.db
DB += dbDataDpmEventState.db
DB += dbDataDpmBlockCount.db
DB += dbDataDpmSystemState.db
DB += dbDataDpmBurnCount.db
DB += dbDataDtmMinTrigPeriod.db
DB += dbDataDpmInsertedFrames.db
DB += dbDataDpmEBEventErrorCount.db
DB += dbFebAll.db
DB += dbBiasAll.db
DB += dbHybridAll.db
DB += dbFebHeartbeat.db
DB += dbHybSyncAll.db
DB += dbHybCurrent.db
DB += dbDataDpmAll.db
DB += dbHybridCurrentAll.db

#DB += dbSVTtest.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_TEMPLATE = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

