TOP = ../..
include $(TOP)/configure/CONFIG
ARCH = linux-x86
TARGETS = envPaths
#envPaths should not be regenerated, so I replaced the RULES.ioc to RULES_DIRS to do nothing. Nerses
#include $(TOP)/configure/RULES.ioc
include $(TOP)/configure/RULES_DIRS
