JAVA_HOME := /apps/java/jdk1.7.0_67
ANT_HOME  := /apps/java/apache-ant-1.9.4
PATH      := ${JAVA_HOME}/bin:${ANT_HOME}/bin:${PATH}

export JAVA_HOME
export ANT_HOME
export PATH

.PHONY: all clean install uninstall print


all:
	ant;

clean:
	ant clean
