dbpf("$(PREFIX)00.DESC","Single-0 Top")
dbpf("$(PREFIX)01.DESC","Single-1 Top")
dbpf("$(PREFIX)02.DESC","Single-2 Top (e+)")
dbpf("$(PREFIX)03.DESC","Single-3 Top (e+/Hodo)")
dbpf("$(PREFIX)04.DESC","Single-0 Bottom")
dbpf("$(PREFIX)05.DESC","Single-1 Bottom")
dbpf("$(PREFIX)06.DESC","Single-2 Bottom (e+)")
dbpf("$(PREFIX)07.DESC","Single-3 Bottom (e+/Hodo)")
dbpf("$(PREFIX)08.DESC","Pair-0 (Old e+e-)")
dbpf("$(PREFIX)09.DESC","Pair-1 (Moller)")
dbpf("$(PREFIX)10.DESC","Pair-2 (2gamma)")
dbpf("$(PREFIX)11.DESC","Pair-3 (mu+mu-)")
dbpf("$(PREFIX)12.DESC","LED")
dbpf("$(PREFIX)13.DESC","Cosmic")
dbpf("$(PREFIX)14.DESC","Hodoscope")
dbpf("$(PREFIX)15.DESC","Pulser")
dbpf("$(PREFIX)16.DESC","Multiplicity-0 (2gamma)")
dbpf("$(PREFIX)17.DESC","Multiplicity-1 (3gamma)")
dbpf("$(PREFIX)18.DESC","FEE Top")
dbpf("$(PREFIX)19.DESC","FEE Bottom")

