dbpf("$(PREFIX)00.DESC","Single-0 Top")
dbpf("$(PREFIX)01.DESC","Single-1 Top")
dbpf("$(PREFIX)02.DESC","Single-2 Top")
dbpf("$(PREFIX)03.DESC","Single-3 Top")
dbpf("$(PREFIX)04.DESC","Single-0 Bottom")
dbpf("$(PREFIX)05.DESC","Single-1 Bottom")
dbpf("$(PREFIX)06.DESC","Single-2 Bottom")
dbpf("$(PREFIX)07.DESC","Single-3 Bottom")
dbpf("$(PREFIX)08.DESC","Pair-0")
dbpf("$(PREFIX)09.DESC","Pair-1")
dbpf("$(PREFIX)10.DESC","Pair-2")
dbpf("$(PREFIX)11.DESC","Pair-3")
dbpf("$(PREFIX)12.DESC","LED")
dbpf("$(PREFIX)13.DESC","Cosmic")
dbpf("$(PREFIX)14.DESC","Hodoscope")
dbpf("$(PREFIX)15.DESC","Pulser")
dbpf("$(PREFIX)16.DESC","Cluster Multiplicity-0")
dbpf("$(PREFIX)17.DESC","Cluster Multiplicity-1")
dbpf("$(PREFIX)18.DESC","FEE Top")
dbpf("$(PREFIX)19.DESC","FEE Bottom")

