#!/bin/env perl
open(OUTPUT,">hv.dat");
$slot = 0;
while ($slot < 16) {
    $group = $slot + 1;
    $chan = 0;
    while ($chan < 12) {
	$dv = 1000 + 12*$slot + $chan;
	if ($slot == 0) {
	    $tc = 30;
	    $maxv = 2500;
	}
	else {
	    $dv = -$dv;
	    $tc = -30;
	    $maxv = -2500;
	}
	print OUTPUT "slot\_$slot\_chan\_$chan $group 1 1 $slot 2 $chan $dv "
	    ."15 5 100 200 $tc $maxv\n";
	$chan++;
    }
    $slot++;
}
close(OUTPUT);
