#!/bin/sh
#
# Wrap with xterm -e
#

echo 'After entering title, left Click in Window for Snapshot'
echo ''
echo 'WARNING:'
echo '  NO OVERLAPPING WINDOWS!' 
echo '  NO SPACES OR SPECIAL CHARACTERS ALLOWED!'
echo ''
echo 'Enter Title ... '
read title

file=$HOME/screenshots/$title\_`date +%Y-%m-%d_%H-%M-%S`.png
import $file

echo 'Saved Screenshot As:'
echo $file
echo ''
echo ''
echo 'Press [enter] to exit.'
read enter
exit 0
